---
title: "Text_mining"
author: "Yingjie"
date: "6/17/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---


# Dir and packages

```{r include=FALSE}
### To clear your environment 
remove(list = ls())

# directories 
source('./Code/_directories.R')


## 1. my data
# dir.pdf  <- paste0(dir.reports, 'pdf_coded_human/')
# dir.coded      <- paste0(dir.pdf, 'DF_coded/');           v <- ''
# dir.coded      <- paste0(dir.pdf, 'DF_tokenize_coded/');  v <- 'tokenize'


## 2. SSFP data
dir.pdf  <- 'G:/Shared drives/gdrive/_paper/SDGs/SDGs_Corporations_g/data/data_pdf_Edmund/'
dir.coded <- paste0(dir.pdf, 'DF_tokenize_coded/');  v <- 'tokenize'



## output directories
dir.coded.comb <- paste0(dir.pdf, 'DF_coded_comb/'); print(dir.coded.comb)


# load packages
source('./Code/_packages.R')
  
today <- format(Sys.time(), "%Y%m%d_%H%M"); today
```


# Data

## Helper data

```{r - UN SGD target list}
source('./Code/helper_UN_SDG_Target_list.R') ## --> ls_un_id; goals_ls

goals_df <- ls_un_id %>%
  dplyr::select(goalname, target_id_un, target_id_un2) %>%
  # group_by(goalname) %>%
  # arrange(goalname, target_id_un2) %>%
  dplyr::mutate(target_id_un = gsub('\\.', '_', target_id_un),
                target_id_un = paste0('SDG', target_id_un)) %>%
  dplyr::mutate(id = row_number()) %>%
  dplyr::mutate(target_id_un = factor(target_id_un, levels = unique(target_id_un)),
                target_id_un = reorder(target_id_un, id)) %>%
  as.data.frame()

## save to `SDG_TM` for R package development
fname <- paste0(dirname(getwd()), '/SDG_TM/data/goals_df.RData'); fname
# save(goals_df, file = fname)
```




# 3. Format results


## coded data with original text

```{r - load coded data}

ls <- list.files(path = dir.coded, pattern = '*.RData$', ignore.case = T, full.names = T); 
# ls

cat('There are', ls %>% length(), 'corporate reports were CODED.')

```


```{r - clean and combine the data, include=FALSE}
coded_combined <- data.frame()

for (f in ls) {
  company_name <- gsub('\\.RData|_coded|\\.pdf', '', basename(f)); 
  # Extract company names (before first "_")
  com_name <- str_extract(company_name, "^[^_]+")
  print(com_name)
  
  # Extract first 4-digit year
  year <- str_extract(company_name, "\\d{4}"); print(year)
  
  load(f) ## all coded reports were named "coded" as Rdata

  ## clean the data 
  coded_i <- coded %>%
    ## only keep the rows with SDG hits
    # filter(n_total > 0) %>%
    mutate(
      company = com_name,
      sdgs    = str_remove(sdgs, "^,"),
      sdgs_n  = str_remove(sdgs_n, "^,"),
      sdgs_n  = str_squish(sdgs_n),
      human_coded = "yes",
      year = year, 
      token_count = str_count(statement, "\\S+")) %>%
    select(-any_of(c('word_count', 'short_word_count'))) %>%
    select(company, everything()) %>%
    as.data.frame()
  
  ## combine data 
  coded_combined <- rbind(coded_combined, coded_i)
}
```




```{r - save combined data - full text}

## count the number of companies
n <- unique(coded_combined$company) %>% length(); n


## count the total tokens
sum(coded_combined$token_count, na.rm = T) %>% 
  round(1) %>% 
  format(big.mark = ",", scientific = F) %>% 
  cat('\nIn total, there are', ., 'tokens in the 2018 dataset.\n\n')


total_tokens <- sum(coded_combined$token_count, na.rm = TRUE)
total_million <- round(total_tokens / 1e6, 2)
cat("\nIn total, there are", total_million, "million tokens in the 2018 dataset, which incldues", n, "companies.\n\n")




## save all the hits to xlsx for easier inspection.
# f <- paste0(dir.coded.comb, 'coded_combined_with_raw_', n, '.xlsx');  f
# writexl::write_xlsx(x = coded_combined, path = f)

csvname <- paste0('coded_combined_all_with_raw_', n, '_', v, '.csv')
f <- file.path(dir.coded.comb, csvname);  f
readr::write_csv(x = coded_combined, file = f)




# f <- paste0(dir.coded.comb, 'coded_combined_with_raw_', n, '.rds'); f
# save(coded_combined, file = f)

```


```{r - save combined data - subset rows with sdgs detected}

coded_combined_sdg <- coded_combined %>%
  ## only keep the rows with SDG hits
  filter(n_total > 0)
  
## count the total tokens
sum(coded_combined_sdg$token_count, na.rm = T) %>% 
  round(1) %>% 
  format(big.mark = ",", scientific = F) %>% 
  cat('\nIn total, there are', ., 'tokens in the 2018 dataset.\n\n')


total_tokens <- sum(coded_combined_sdg$token_count, na.rm = TRUE)
total_million <- round(total_tokens / 1e6, 2)
cat("\nIn total, there are", total_million, "million tokens in the 2018 dataset, which incldues", n, "companies.\n\n")




## save all the hits to xlsx for easier inspection.
# f <- paste0(dir.coded.comb, 'coded_combined_sdg_with_raw_', n, '.xlsx');  f
# writexl::write_xlsx(x = coded_combined_sdg, path = f)


csvname <- paste0('coded_combined_sdg_with_raw_', n, '_', v, '.csv')
f <- paste0(dir.coded.comb, csvname);  f
readr::write_csv(x = coded_combined_sdg, file = f)


## make a copy for LLM test 
f <- file.path('./data/data_tm/coded_combined_results', csvname);  f
readr::write_csv(x = coded_combined_sdg, file = f)


# f <- paste0(dir.coded.comb, 'coded_combined_with_raw_', n, '.rds'); f
# save(coded_combined, file = f)

```


## coded data with only sdg counts

```{r - function}

func_format <- function(coded) {
  
  ### --> pull out the column with coded results
  # coded_sdgs <- dplyr::pull(coded, sdgs)   ## the same as below one
  coded_sdgs <- as.vector(unlist(coded['sdgs'])) %>%
    paste(sep = " ", collapse = " ")
  # coded_sdgs
  
  
  ### --> format it as a DF 
  coded_sdgs <- unlist(strsplit(coded_sdgs, split = "\\,")) %>% trimws();
    
  coded_sdgs_df <- as.data.frame(table(coded_sdgs)) %>%
    dplyr::filter(coded_sdgs != '') %>%
    separate(col = coded_sdgs, into = c('goal', 'target_id'), sep = '_', remove = F) %>%
    dplyr::mutate(
      goal_id   = as.numeric(gsub("\\D", "", goal)),
      target_id = gsub('^.{3}', "", coded_sdgs)) %>%
    arrange(goal_id, target_id) %>%
    dplyr::select(1:2, goal_id, everything()) %>%
    dplyr::rename(n_statements = Freq)
  
  
  
  ### --> The above data only presents what were detected, but some SDGs without match won't be shown. 
  ### --> Force to list all 17 SDGs and 169 Targets

  
  ### --> merge data 
  coded_sdgs_df_format <- 
    merge(x = coded_sdgs_df, ## the coded data
          y = goals_df,      ## the UN goal and target id for formatting
          by.x = c('goal', 'coded_sdgs'), 
          by.y = c('goalname', 'target_id_un'), all = T) %>%
    dplyr::mutate(goal = factor(goal, levels = goals_ls)) %>%
    arrange(goal, id) %>%
    dplyr::mutate(id = row_number()) %>%
    dplyr::mutate(coded_sdgs = gsub('general', 'g', coded_sdgs),
                  coded_sdgs = factor(coded_sdgs, levels = unique(coded_sdgs)),
                  coded_sdgs = reorder(coded_sdgs, id)) %>%
    ## for the NA in `goal_id` and `target_id`, fill the info
    dplyr::mutate(
      goal_id   = ifelse(is.na(goal_id),   gsub('SDG|\\_.*$','',coded_sdgs), goal_id),
      # target_id = ifelse(is.na(target_id), gsub('.*_','',coded_sdgs), target_id), ## Remove all text before '_'
      target_id = ifelse(is.na(target_id), gsub('SDG','',coded_sdgs), target_id) ## Remove all text before '_'
    ) %>%
    as.data.frame()
  
  # str(coded_sdgs_df_format)
  return(coded_sdgs_df_format)

}

```




```{r - run}

dfs <- data.frame()

for (f in ls) {
  # print(f)
  company_name <- gsub('\\.RData|_coded|\\.pdf', '', basename(f)); 
  # Extract company names (before first "_")
  com_name <- str_extract(company_name, "^[^_]+")
  print(com_name)
  
  load(f) ## all coded reports were named "coded" as Rdata

  d <- func_format(coded = coded)
  d$company = com_name
  d <- d %>% dplyr::select(company, everything())

  dfs <- rbind(dfs, d)
}

n <- unique(dfs$company) %>% length(); n

### save all the hits to xlsx for easier inspection. 
fname <- paste0(dir.coded.comb, 'coded_dfs_', n, '_', v, '.xlsx');  fname
writexl::write_xlsx(x = dfs, path = fname)

fname <- paste0(dir.coded.comb, 'coded_dfs_', n, '_', v, '.RData'); fname
save(dfs, file = fname)

```





* 4. Compare Machine to Human - next script

  `See next script`. 

